
GET http://localhost:4000/api/files 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjhAZ21haWwuY29tIiwiaWF0IjoxNjcyNzM4NzU3LCJleHAiOjE2NzI3Mzg4MTd9.0pN67vDvasjEE4Cxxur1MX-ORo0jBJ9s08PGxmS8Iks


###

POST http://localhost:4000/api/token
content-type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjhAZ21haWwuY29tIiwiaWF0IjoxNjcyNzM4NjkxfQ.LIyhvnNefucF8zq6yg9OwWH8YgLsVlc0Ok9BdliUHu8"
}
###
POST http://localhost:4000/api/register
content-type: application/json

  {
  "email":"8@gmail.com",
  "password":"43DfdfdsfsdSD"
  } 
###
POST http://localhost:4000/api/login
content-type: application/json

  {
  "email":"8@gmail.com",
  "password":"43DfdfdsfsdSD"
  } 